'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useToast } from '@/components/ui/Toast';
import Button from '@/components/ui/Button';
import { 
  Save, 
  ArrowLeft, 
  Sparkles, 
  Globe, 
  Search, 
  Code,
  Eye,
  Type
} from 'lucide-react';
import type { Blog } from '@/lib/db/schema';

interface BlogEditorProps {
  blog?: Blog;
  locale: string;
}

export default function BlogEditor({ blog, locale }: BlogEditorProps) {
  const { toast } = useToast();
  const router = useRouter();
  
  const [isSaving, setIsSaving] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [prompt, setPrompt] = useState('');
  
  const [formData, setFormData] = useState({
    title: blog?.title || '',
    slug: blog?.slug || '',
    description: blog?.description || '',
    content: blog?.content as string || '',
    keywords: blog?.keywords || '',
    status: blog?.status || 'DRAFT',
    seoTitle: blog?.seoTitle || '',
    seoDescription: blog?.seoDescription || '',
    schemaData: blog?.schemaData || {},
  });

  const [activeTab, setActiveTab] = useState<'content' | 'seo' | 'preview'>('content');

  const handleSave = async () => {
    if (!formData.title || !formData.slug) {
      toast('Title and Slug are required', 'error');
      return;
    }

    setIsSaving(true);
    try {
      const url = blog ? `/api/admin/blogs/${blog.id}` : '/api/admin/blogs';
      const method = blog ? 'PATCH' : 'POST';
      
      const res = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData),
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || 'Failed to save');
      }

      toast(`Blog post ${blog ? 'updated' : 'created'} successfully!`, 'success');
      if (!blog) {
        router.push(`/${locale}/admin/blogs`);
      }
      router.refresh();
    } catch (error) {
      toast((error as Error).message, 'error');
    } finally {
      setIsSaving(false);
    }
  };

  const handleGenerate = async () => {
    if (!prompt) {
      toast('Please enter a prompt for the AI', 'error');
      return;
    }

    setIsGenerating(true);
    try {
      const res = await fetch('/api/admin/blogs/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt }),
      });

      if (!res.ok) throw new Error('Failed to generate content');
      
      const data = await res.json();
      setFormData({
        ...formData,
        title: data.title || formData.title,
        slug: data.slug || formData.slug,
        description: data.description || formData.description,
        content: data.content || formData.content,
        keywords: data.keywords || formData.keywords,
        seoTitle: data.seoTitle || formData.seoTitle,
        seoDescription: data.seoDescription || formData.seoDescription,
        schemaData: data.schemaData || formData.schemaData,
      });
      
      toast('Blog content generated by AI!', 'success');
    } catch (error) {
      toast('AI generation failed', 'error');
    } finally {
      setIsGenerating(false);
    }
  };

  // Auto-generate slug from title
  useEffect(() => {
    if (!blog && formData.title && !formData.slug) {
      const suggestedSlug = formData.title
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/(^-|-$)/g, '');
      setFormData(prev => ({ ...prev, slug: suggestedSlug }));
    }
  }, [formData.title, blog]);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-4">
        <button
          onClick={() => router.back()}
          className="flex items-center gap-2 text-[var(--fg)]/60 hover:text-[var(--fg)]"
        >
          <ArrowLeft className="h-5 w-5" />
          Back to list
        </button>
        <div className="flex items-center gap-3">
          <select
            value={formData.status}
            onChange={(e) => setFormData({ ...formData, status: e.target.value as any })}
            className="rounded-xl border border-[var(--border-color)] bg-[var(--surface)] px-3 py-2 outline-none"
          >
            <option value="DRAFT">Draft</option>
            <option value="PUBLISHED">Published</option>
          </select>
          <Button onClick={handleSave} isLoading={isSaving}>
            <Save className="mr-2 h-5 w-5" />
            {blog ? 'Update Blog' : 'Create Blog'}
          </Button>
        </div>
      </div>

      <div className="grid gap-8 lg:grid-cols-3">
        {/* Main Content Area */}
        <div className="lg:col-span-2 space-y-6">
          {/* AI Generator Box */}
          <div className="rounded-2xl border-2 border-dashed border-primary-500/30 bg-primary-500/5 p-6">
            <h3 className="flex items-center gap-2 text-lg font-bold text-primary-600 dark:text-primary-400">
              <Sparkles className="h-5 w-5" />
              AI Blog Generator
            </h3>
            <p className="mt-1 text-sm text-[var(--fg)]/60">
              Enter a topic or outline and let GPT-5-mini write the blog, SEO settings, and schemas for you.
            </p>
            <div className="mt-4 flex gap-2">
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="e.g. Write a comprehensive guide about 10 essential French medical terms for travelers..."
                className="flex-1 rounded-xl border border-[var(--border-color)] bg-[var(--bg)] p-3 text-sm outline-none focus:border-primary-500"
                rows={2}
              />
              <Button
                variant="secondary"
                onClick={handleGenerate}
                isLoading={isGenerating}
                className="h-auto"
              >
                Generate
              </Button>
            </div>
          </div>

          {/* Form Tabs */}
          <div className="flex border-b border-[var(--border-color)]">
            <button
              onClick={() => setActiveTab('content')}
              className={cn(
                "px-6 py-3 font-semibold transition-colors",
                activeTab === 'content' ? "border-b-2 border-primary-500 text-primary-500" : "text-[var(--fg)]/40 hover:text-[var(--fg)]"
              )}
            >
              Content
            </button>
            <button
              onClick={() => setActiveTab('seo')}
              className={cn(
                "px-6 py-3 font-semibold transition-colors",
                activeTab === 'seo' ? "border-b-2 border-primary-500 text-primary-500" : "text-[var(--fg)]/40 hover:text-[var(--fg)]"
              )}
            >
              SEO & Schema
            </button>
            <button
              onClick={() => setActiveTab('preview')}
              className={cn(
                "px-6 py-3 font-semibold transition-colors",
                activeTab === 'preview' ? "border-b-2 border-primary-500 text-primary-500" : "text-[var(--fg)]/40 hover:text-[var(--fg)]"
              )}
            >
              Live Preview
            </button>
          </div>

          {activeTab === 'content' && (
            <div className="space-y-4 animate-in fade-in slide-in-from-bottom-2">
              <div>
                <label className="mb-1 block text-sm font-bold text-[var(--fg)]/60">Blog Title</label>
                <input
                  type="text"
                  value={formData.title}
                  onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                  placeholder="The Ultimate Guide to..."
                  className="w-full rounded-xl border border-[var(--border-color)] bg-[var(--surface)] p-4 text-xl font-bold outline-none focus:border-primary-500"
                />
              </div>
              <div>
                <label className="mb-1 block text-sm font-bold text-[var(--fg)]/60">Full Content (HTML)</label>
                <textarea
                  value={formData.content}
                  onChange={(e) => setFormData({ ...formData, content: e.target.value })}
                  placeholder="<p>Welcome to our blog...</p> <h2>Chapter 1</h2>..."
                  className="h-[500px] w-full rounded-xl border border-[var(--border-color)] bg-[var(--surface)] p-4 font-mono text-sm outline-none focus:border-primary-500"
                />
              </div>
            </div>
          )}

          {activeTab === 'seo' && (
            <div className="space-y-4 animate-in fade-in slide-in-from-bottom-2">
              <div className="grid gap-4 sm:grid-cols-2">
                <div>
                  <label className="mb-1 block text-sm font-bold text-[var(--fg)]/60">SEO Title</label>
                  <input
                    type="text"
                    value={formData.seoTitle}
                    onChange={(e) => setFormData({ ...formData, seoTitle: e.target.value })}
                    className="w-full rounded-xl border border-[var(--border-color)] bg-[var(--surface)] p-3 outline-none"
                  />
                </div>
                <div>
                  <label className="mb-1 block text-sm font-bold text-[var(--fg)]/60">Keywords</label>
                  <input
                    type="text"
                    value={formData.keywords}
                    onChange={(e) => setFormData({ ...formData, keywords: e.target.value })}
                    placeholder="french, medical, vocabulary"
                    className="w-full rounded-xl border border-[var(--border-color)] bg-[var(--surface)] p-3 outline-none"
                  />
                </div>
              </div>
              <div>
                <label className="mb-1 block text-sm font-bold text-[var(--fg)]/60">SEO Description</label>
                <textarea
                  value={formData.seoDescription}
                  onChange={(e) => setFormData({ ...formData, seoDescription: e.target.value })}
                  rows={3}
                  className="w-full rounded-xl border border-[var(--border-color)] bg-[var(--surface)] p-3 outline-none"
                />
              </div>
              <div>
                <label className="mb-1 block text-sm font-bold text-[var(--fg)]/60">Schema Data (JSON-LD)</label>
                <textarea
                  value={JSON.stringify(formData.schemaData, null, 2)}
                  onChange={(e) => {
                    try {
                      const parsed = JSON.parse(e.target.value);
                      setFormData({ ...formData, schemaData: parsed });
                    } catch (err) {}
                  }}
                  rows={10}
                  className="w-full rounded-xl border border-[var(--border-color)] bg-[var(--surface)] p-4 font-mono text-xs outline-none focus:border-primary-500"
                />
              </div>
            </div>
          )}

          {activeTab === 'preview' && (
            <div className="prose prose-lg dark:prose-invert max-w-none rounded-2xl border border-[var(--border-color)] bg-[var(--surface)] p-8 animate-in fade-in slide-in-from-bottom-2">
              <h1>{formData.title}</h1>
              <div dangerouslySetInnerHTML={{ __html: formData.content }} />
            </div>
          )}
        </div>

        {/* Sidebar Settings */}
        <div className="space-y-6">
          <div className="rounded-2xl border border-[var(--border-color)] bg-[var(--surface)] p-6">
            <h3 className="mb-4 font-bold">Post Settings</h3>
            <div className="space-y-4">
              <div>
                <label className="mb-1 block text-xs font-bold uppercase text-[var(--fg)]/40">URL Slug</label>
                <div className="flex items-center rounded-xl border border-[var(--border-color)] bg-[var(--bg)] px-3">
                  <span className="text-sm text-[var(--fg)]/30">/blogs/</span>
                  <input
                    type="text"
                    value={formData.slug}
                    onChange={(e) => setFormData({ ...formData, slug: e.target.value })}
                    className="flex-1 bg-transparent py-2 text-sm outline-none"
                  />
                </div>
              </div>
              <div>
                <label className="mb-1 block text-xs font-bold uppercase text-[var(--fg)]/40">Short Excerpt</label>
                <textarea
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  rows={4}
                  className="w-full rounded-xl border border-[var(--border-color)] bg-[var(--bg)] p-3 text-sm outline-none"
                  placeholder="Sum it up in 2-3 sentences..."
                />
              </div>
            </div>
          </div>

          <div className="rounded-2xl border border-[var(--border-color)] bg-[var(--surface)] p-6">
            <h3 className="mb-4 font-bold flex items-center gap-2">
              <Globe className="h-4 w-4" />
              SEO Preview
            </h3>
            <div className="space-y-1 overflow-hidden">
              <p className="truncate text-xs text-blue-800 dark:text-blue-400">lingdb.com › blogs › {formData.slug}</p>
              <h4 className="line-clamp-2 text-lg font-medium text-blue-600 dark:text-blue-400 group-hover:underline">
                {formData.seoTitle || formData.title || 'Untitled Blog Post'}
              </h4>
              <p className="line-clamp-3 text-sm text-[var(--fg)]/60">
                {formData.seoDescription || formData.description || 'No description provided...'}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function cn(...classes: (string | boolean | undefined)[]) {
  return classes.filter(Boolean).join(' ');
}
